<?php
http_response_code(404);
?><!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Trongate</title>
</head>
<body>

    <h1>404 Error : Page Not Found</h1>
    <p>This page is being generated by the Trongate Framework.</p>
    <p>To edit this page, go to: templates/views/error_404.php</p>
    <p>To explore the documentation go to <a href="http://www.trongate.io/documentation">http://www.trongate.io/documentation</a></p>
    
    <style>
        body {
            font-size: 2em;
            background: #ff0000;
            color: #ddd;
            text-align: center;
            font-family: "Lucida Console", Monaco, monospace;
        }

        h1 {
            margin-top: 2em;
        }

        h1, h2 {
            text-transform: uppercase;
        }

        a { color: white; }
    </style>
</body>
</html>